### ISSUE TITLE
⚠️ 3D Secure not supported ⚠️

### ISSUE THREAD

**Issue by alexjamesbrown** [eltrino/magento2-hyva-checkout-stripe#5]
This doesn't support 3D Secure / callbacks.

**Comment by kulbich** [comment]
> This doesn't support 3D Secure / callbacks.

Hi @alexjamesbrown we'll check it. Thank you!

**Comment by kulbich** [comment]
@alexjamesbrown The issue has been resolved. Thank you for reporting it.
