### ISSUE TITLE
Duplicate Payment in Stripe

### ISSUE THREAD

**Issue by mustanguy69** [eltrino/magento2-hyva-checkout-stripe#8]
Hello,

Thanks for a great module !
I am having an issue where every payment is duplicated in Stripe...

Is there any configuration I missed in Magento or Stripe to avaoid that ?

Regards
T

**Comment by rostilos** [comment]
You're not alone. We also implemented a module on one of our large projects with Hyva Theme and encountered a double-charge. This is a problem of the module and its irrelevance for new Stripe versions, it is not so difficult to fix, I will try to help you and provide you with sample code with edits (I remember that there is a problem with session caches).
But I want to warn you: earlier we faced with the fact that the functionality for payments with 3ds is not implemented and we had to finalize it ourselves, which was not a small part of the changes for correct operation

**Comment by mustanguy69** [comment]
Thanks, I would love some help if you can ?

Also for The 3ds, I have been trying with some test cards it has worked fine ?

Let me know
Thanks again
T

**Comment by rostilos** [comment]
**
Post removed, as I see the module has changed significantly since it was installed by our team on the project and my edits will be irrelevant at this time 
***

**Comment by kulbich** [comment]
@mustanguy69 thank you 🙂 Are you using the latest version? It was fixed already.

**Comment by mustanguy69** [comment]
@rostilos thanks a lot I will review, it can be a clue anyway!

@kulbich last version of this module or the Magento one ?

**Comment by kulbich** [comment]
@mustanguy69 of the module

**Comment by mustanguy69** [comment]
Pulling last changes, made it work ! 
thank you so much for your quick help !
